version: "3"
services:
  web:
    image: devsda/docker_file_heirarchy:v2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "9090:8080"
    networks:
      - webnet
networks:
  webnet: